name: Certificates

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - name: Clone the repo on machine
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_DEPLOY_KEY }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 
